CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- statement-breakpoint

CREATE TABLE IF NOT EXISTS organizations (
  id text PRIMARY KEY,
  name text NOT NULL UNIQUE,
  official_url text,
  verification_status text NOT NULL DEFAULT 'unverified'
    CHECK (verification_status IN ('unverified', 'official_source_confirmed')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- statement-breakpoint

CREATE TABLE IF NOT EXISTS qualifications (
  id text PRIMARY KEY,
  name text NOT NULL,
  organization_id text NOT NULL REFERENCES organizations(id),
  category text NOT NULL,
  parent_qualification_id text REFERENCES qualifications(id),
  keywords text[] NOT NULL DEFAULT '{}',
  active boolean NOT NULL DEFAULT true,
  verification_status text NOT NULL DEFAULT 'catalog_only'
    CHECK (verification_status IN ('catalog_only', 'official_source_confirmed')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (name, organization_id)
);

-- statement-breakpoint

CREATE INDEX IF NOT EXISTS qualifications_search_idx
  ON qualifications USING gin (name gin_trgm_ops);

-- statement-breakpoint

CREATE INDEX IF NOT EXISTS qualifications_keywords_idx
  ON qualifications USING gin (keywords);

-- statement-breakpoint

CREATE TABLE IF NOT EXISTS source_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  qualification_id text REFERENCES qualifications(id),
  organization_id text REFERENCES organizations(id),
  title text NOT NULL,
  source_url text NOT NULL UNIQUE,
  system_type text NOT NULL DEFAULT 'unspecified',
  acquired_year_from integer,
  acquired_year_to integer,
  renewal_year_from integer,
  renewal_year_to integer,
  media_type text NOT NULL DEFAULT 'auto'
    CHECK (media_type IN ('auto', 'html', 'pdf')),
  is_index boolean NOT NULL DEFAULT false,
  discovery_keywords text[] NOT NULL DEFAULT '{}',
  active boolean NOT NULL DEFAULT true,
  fetch_interval_hours integer NOT NULL DEFAULT 168 CHECK (fetch_interval_hours >= 1),
  last_checked_at timestamptz,
  last_changed_at timestamptz,
  last_http_status integer,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    acquired_year_from IS NULL OR acquired_year_to IS NULL
    OR acquired_year_from <= acquired_year_to
  ),
  CHECK (
    renewal_year_from IS NULL OR renewal_year_to IS NULL
    OR renewal_year_from <= renewal_year_to
  )
);

-- statement-breakpoint

CREATE INDEX IF NOT EXISTS source_documents_due_idx
  ON source_documents (active, last_checked_at, fetch_interval_hours);

-- statement-breakpoint

CREATE TABLE IF NOT EXISTS source_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_document_id bigint NOT NULL REFERENCES source_documents(id),
  fetched_at timestamptz NOT NULL DEFAULT now(),
  checked_at timestamptz NOT NULL DEFAULT now(),
  http_status integer NOT NULL,
  content_type text NOT NULL,
  sha256 text NOT NULL,
  byte_length integer NOT NULL,
  blob_path text NOT NULL,
  blob_url text NOT NULL,
  etag text,
  last_modified text,
  extracted_text text,
  extraction_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_document_id, sha256)
);

-- statement-breakpoint

CREATE TABLE IF NOT EXISTS renewal_rule_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  qualification_id text NOT NULL REFERENCES qualifications(id),
  source_snapshot_id bigint NOT NULL REFERENCES source_snapshots(id),
  system_type text NOT NULL,
  acquired_year_from integer,
  acquired_year_to integer,
  renewal_year_from integer,
  renewal_year_to integer,
  valid_from date,
  valid_to date,
  renewal_cycle_years numeric,
  required_total_credits numeric,
  structured_data jsonb NOT NULL,
  extraction_method text NOT NULL DEFAULT 'deterministic-v1',
  confidence numeric NOT NULL DEFAULT 0 CHECK (confidence >= 0 AND confidence <= 1),
  status text NOT NULL DEFAULT 'pending_review'
    CHECK (status IN ('pending_review', 'published', 'rejected', 'superseded')),
  reviewed_at timestamptz,
  published_at timestamptz,
  supersedes_id bigint REFERENCES renewal_rule_versions(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (qualification_id, source_snapshot_id, system_type)
);

-- statement-breakpoint

CREATE INDEX IF NOT EXISTS renewal_rule_lookup_idx
  ON renewal_rule_versions (
    qualification_id, status, system_type,
    acquired_year_from, acquired_year_to
  );

-- statement-breakpoint

CREATE TABLE IF NOT EXISTS ingestion_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trigger_type text NOT NULL,
  status text NOT NULL CHECK (status IN ('running', 'succeeded', 'partial', 'failed')),
  sources_checked integer NOT NULL DEFAULT 0,
  sources_changed integer NOT NULL DEFAULT 0,
  rules_proposed integer NOT NULL DEFAULT 0,
  errors jsonb NOT NULL DEFAULT '[]'::jsonb,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz
);
