CREATE TABLE IF NOT EXISTS app_invites (
  code_hash text PRIMARY KEY,
  email text,
  email_domain text,
  max_uses integer NOT NULL DEFAULT 1 CHECK (max_uses >= 1),
  use_count integer NOT NULL DEFAULT 0 CHECK (use_count >= 0),
  expires_at timestamptz,
  revoked_at timestamptz,
  created_by text NOT NULL DEFAULT 'admin',
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (email IS NULL OR email = lower(email)),
  CHECK (email_domain IS NULL OR email_domain = lower(email_domain))
);

-- statement-breakpoint

CREATE TABLE IF NOT EXISTS app_users (
  user_id text PRIMARY KEY,
  email text NOT NULL,
  display_name text,
  invitation_hash text REFERENCES app_invites(code_hash),
  invited_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (email = lower(email))
);

-- statement-breakpoint

CREATE INDEX IF NOT EXISTS app_users_email_idx ON app_users (email);

-- statement-breakpoint

CREATE TABLE IF NOT EXISTS user_snapshots (
  user_id text PRIMARY KEY REFERENCES app_users(user_id) ON DELETE CASCADE,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- statement-breakpoint

CREATE TABLE IF NOT EXISTS user_attachments (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES app_users(user_id) ON DELETE CASCADE,
  blob_path text NOT NULL UNIQUE,
  original_name text NOT NULL,
  content_type text NOT NULL,
  byte_length integer NOT NULL CHECK (byte_length > 0),
  sha256 text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- statement-breakpoint

CREATE INDEX IF NOT EXISTS user_attachments_user_idx
  ON user_attachments (user_id, created_at DESC);

-- statement-breakpoint

CREATE TABLE IF NOT EXISTS user_backups (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES app_users(user_id) ON DELETE CASCADE,
  revision bigint NOT NULL CHECK (revision >= 0),
  blob_path text NOT NULL UNIQUE,
  sha256 text NOT NULL,
  byte_length integer NOT NULL CHECK (byte_length > 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- statement-breakpoint

CREATE INDEX IF NOT EXISTS user_backups_user_idx
  ON user_backups (user_id, created_at DESC);

-- statement-breakpoint

CREATE TABLE IF NOT EXISTS web_push_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL REFERENCES app_users(user_id) ON DELETE CASCADE,
  endpoint_hash text NOT NULL UNIQUE,
  endpoint text NOT NULL,
  p256dh text NOT NULL,
  auth text NOT NULL,
  expiration_time bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- statement-breakpoint

CREATE INDEX IF NOT EXISTS web_push_subscriptions_user_idx
  ON web_push_subscriptions (user_id);

-- statement-breakpoint

CREATE TABLE IF NOT EXISTS web_push_deliveries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL REFERENCES app_users(user_id) ON DELETE CASCADE,
  subscription_id bigint NOT NULL REFERENCES web_push_subscriptions(id) ON DELETE CASCADE,
  notification_key text NOT NULL,
  sent_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (subscription_id, notification_key)
);
